Update pull_request_checks.yml

diff --git a/.github/workflows/pull_request_checks.yml b/.github/workflows/pull_request_checks.yml
--- a/.github/workflows/pull_request_checks.yml
+++ b/.github/workflows/pull_request_checks.yml
@@ -7,25 +7,28 @@ on:
       - synchronize
 
 jobs:
-  checks:
+  check_template:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Run ESLint
-        run: npx eslint --ignore-path .gitignore .
-
-      - name: Update Pull Request Template
+      - name: Verify checkboxes
         run: |
-          echo "### Points à valider avant de merge" >> $GITHUB_EVENT_PATH
-          echo "- [ ] Est-ce que le pull-request est dans une branche connecté sur Jira?" >> $GITHUB_EVENT_PATH
-          echo "- [ ] Est-ce qu'un test a été fait pour les fonctions ajoutées et ont été testés localement?" >> $GITHUB_EVENT_PATH
-          echo "- [ ] As-tu update le ReadMe avec les nouveau éléments ajoutées?" >> $GITHUB_EVENT_PATH
-          echo "- [ ] As-tu bien commenté ton code?" >> $GITHUB_EVENT_PATH
-          cat $GITHUB_EVENT_PATH
-          mv $GITHUB_EVENT_PATH $GITHUB_EVENT_PATH.json
+          PR_TEMPLATE_PATH=".github/pull_request_template.md"
+          CHECKMARK="[x]"
+
+          # Check if the PR template file exists
+          if [ -f "$PR_TEMPLATE_PATH" ]; then
+            # Check if all checkboxes are checked
+            if grep -q "$CHECKMARK" "$PR_TEMPLATE_PATH"; then
+              echo "All checkboxes are checked. PR template validation successful!"
+            else
+              echo "ERROR: Some checkboxes are not checked in the PR template."
+              exit 1
+            fi
+          else
+            echo "ERROR: PR template file not found."
+            exit 1
+          fi
